trivial: Resolve Python 3 issues
Resolve the following exception:

  AttributeError: 'str' object has no attribute 'decode'

This wasn't caught in the gate because that still uses Python 2.7. This
is not the case in other environments (Fedora 27).

Change-Id: I6b462f19432c4cf9948cddcc095d9d5a85feeb4b